### ISSUE TITLE
for-loop of O(Log N) resulted infinite executions.

### ISSUE THREAD

**Issue by gerosprime** [cooervo/Algorithms-DataStructures-BigONotation#10]
Hi,

I believe this is a typo error.
```

for(int i=0; i < n; i *= 2) {
       //do something in constant time...
}	
```

could be
```

for(int i=1; i < n; i *= 2) {
        //do something in constant time...
}	
```

But hey, many thanks for making me closer to understand O(Log N) and O(N * Log N). It really helps!

**Comment by cooervo** [comment]
this was not intenteded to be executable code, just kind of a pseudo code to understand the idea
